// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcuOhen1ZlH6hj6N7fJ4LOHQ0En76Br3Y',
    appId: '1:201251851950:web:518c36e5a331265f76e73f',
    messagingSenderId: '201251851950',
    projectId: 'getx-3',
    authDomain: 'getx-3.firebaseapp.com',
    storageBucket: 'getx-3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjm55ynyqgfQANx-oKdaD96Z9qi_O4L6M',
    appId: '1:201251851950:android:4ec8e841d1da502f76e73f',
    messagingSenderId: '201251851950',
    projectId: 'getx-3',
    storageBucket: 'getx-3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC61gUYQXYLQLc7aQjYayHmcoZBV5Gk_O8',
    appId: '1:201251851950:ios:150b4bd45ee78f1376e73f',
    messagingSenderId: '201251851950',
    projectId: 'getx-3',
    storageBucket: 'getx-3.appspot.com',
    iosClientId: '201251851950-3b4arpq8jui6f9sm86q05kl0qnllde64.apps.googleusercontent.com',
    iosBundleId: 'com.example.get',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC61gUYQXYLQLc7aQjYayHmcoZBV5Gk_O8',
    appId: '1:201251851950:ios:4c7a0339f76a1e6476e73f',
    messagingSenderId: '201251851950',
    projectId: 'getx-3',
    storageBucket: 'getx-3.appspot.com',
    iosClientId: '201251851950-qcb024bhsbe4eclpk3bi01a9eps2so26.apps.googleusercontent.com',
    iosBundleId: 'com.example.get.RunnerTests',
  );
}
